filename1 = input("Enter the name of the first file: ")
filename2 = input("Enter the name of the second file: ")
f1 = open(filename1, 'r')
text = f1.read()
f1.close()
f2 = open(filename2, 'w')
f2.write(text)
f2.close()
print("Here is what you've copied:")
print(text)